server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@//jjan.cjqjlsbobugz.ap-northeast-2.rds.amazonaws.com:1521/jjan
    username: admin05
    password: kbitisyourlife33

  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: create  # update
    properties:
      hibernate:
        show_sql: true  # ??? sql ??
        format_sql: true   # sql ????? ??
        use_sql_comments: true;   # ???? ?? comment ?? ??
    show_sql: true
